# Static IP for a server called 'server01'
# host-record=<hostname>,<IP_address>
host-record=pihole,192.168.1.53
host-record=pihole.home.local,192.168.1.53

host-record=services,192.168.1.100
host-record=services.home.local,192.168.1.100
host-record=traefik.devdotweb.com,192.168.1.100
host-record=pihole.devdotweb.com,192.168.1.100
host-record=vault.devdotweb.com,192.168.1.100
host-record=vault.home.local,192.168.1.100
host-record=gitlab.devdotweb.com,192.168.1.100
host-record=gitlab.home.local,192.168.1.100
host-record=pgadmin.home.local,192.168.1.100
host-record=pgadmin.devdotweb.com,192.168.1.100
host-record=postgres.home.local,192.168.1.100
host-record=postgres.devdotweb.com,192.168.1.100
host-record=minio.home.local,192.168.1.100
host-record=minio.devdotweb.com,192.168.1.100

host-record=k3s-node1.home.local,192.168.1.200
host-record=k3s-node1,192.168.1.200

# Multiple hostnames pointing to the same IP
#host-record=router.home.local,192.168.1.1
#host-record=gateway.home.local,192.168.1.1
